# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - release
  - devel

env:
  - _R_CHECK_FORCE_SUGGESTS_=0
  - NOT_CRAN=1
  
cache: packages

r_packages:
  - covr

addons:
  apt:
    update: true
    packages:
      - libmpfr-dev
      - libglpk-dev

sudo: false

script: 
  - |
    R CMD build .
    travis_wait 50 R CMD check CVXR*tar.gz
    
after_success:
  - travis_wait 50 Rscript -e 'covr::codecov()'

notifications:
  email: false
